lib/live_map_view_web/router.ex
defmodule LiveMapViewWeb.Router do
  use LiveMapViewWeb, :router

  import LiveMapViewWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {LiveMapViewWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LiveMapViewWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  scope "/api", LiveMapViewWeb do
    pipe_through :api

    post "/log_in", UserApiSessionController, :create
  end

  scope "/api", LiveMapViewWeb do
    pipe_through [:api, :require_verify_header]

    resources "/maps", MapController, except: [:new, :edit]
    resources "/points", PointController, only: [:create]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: LiveMapViewWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", LiveMapViewWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", LiveMapViewWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    live "/maps", MapLive.Index, :index
    live "/maps/new", MapLive.Index, :new
    live "/maps/:id/edit", MapLive.Index, :edit

    live "/maps/:id", MapLive.Show, :show
    live "/maps/:id/show/edit", MapLive.Show, :edit
  end

  scope "/", LiveMapViewWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/live_map_view_web/live/live_helpers.ex
defmodule LiveMapViewWeb.LiveHelpers do
  import Phoenix.LiveView.Helpers

  @doc """
  Renders a component inside the `LiveMapViewWeb.ModalComponent` component.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <%= live_modal LiveMapViewWeb.MapLive.FormComponent,
        id: @map.id || :new,
        action: @live_action,
        map: @map,
        return_to: Routes.map_index_path(@socket, :index) %>
  """
  def live_modal(component, opts) do
    path = Keyword.fetch!(opts, :return_to)
    modal_opts = [id: :modal, return_to: path, component: component, opts: opts]
    live_component(LiveMapViewWeb.ModalComponent, modal_opts)
  end
end

lib/live_map_view_web/live/map_live/form_component.ex
defmodule LiveMapViewWeb.MapLive.FormComponent do
  use LiveMapViewWeb, :live_component

  alias LiveMapView.Loggers

  @impl true
  def update(%{map: map} = assigns, socket) do
    changeset = Loggers.change_map(map)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"map" => map_params}, socket) do
    changeset =
      socket.assigns.map
      |> Loggers.change_map(map_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"map" => map_params}, socket) do
    save_map(socket, socket.assigns.action, map_params)
  end

  defp save_map(socket, :edit, map_params) do
    case Loggers.update_map(socket.assigns.map, map_params) do
      {:ok, _map} ->
        {:noreply,
         socket
         |> put_flash(:info, "Map updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_map(socket, :new, map_params) do
    case Loggers.create_map(map_params) do
      {:ok, _map} ->
        {:noreply,
         socket
         |> put_flash(:info, "Map created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/live_map_view_web/live/map_live/index.ex
defmodule LiveMapViewWeb.MapLive.Index do
  use LiveMapViewWeb, :live_view

  alias LiveMapView.Loggers
  alias LiveMapView.Loggers.Map

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :maps, list_maps())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Map")
    |> assign(:map, Loggers.get_map!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Map")
    |> assign(:map, %Map{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Maps")
    |> assign(:map, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    map = Loggers.get_map!(id)
    {:ok, _} = Loggers.delete_map(map)

    {:noreply, assign(socket, :maps, list_maps())}
  end

  defp list_maps do
    Loggers.list_maps()
  end
end

lib/live_map_view_web/live/map_live/show.ex
defmodule LiveMapViewWeb.MapLive.Show do
  use LiveMapViewWeb, :live_view

  alias LiveMapView.Loggers
  alias LiveMapViewWeb.Presence

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    topic = "map:#{id}"
    Phoenix.PubSub.subscribe(LiveMapView.PubSub, topic)
    setup_presence_data(id)

    devices = Presence.list_presence(topic)

    markers =
      Enum.map(devices, fn d ->
        %{
          device_id: d.current_location.device_id,
          lat: d.current_location.lat,
          lng: d.current_location.lng
        }
      end)

    {
      :noreply,
      socket
      |> assign(:page_title, page_title(socket.assigns.live_action))
      |> assign(:map, Loggers.get_map!(id))
      |> assign(:devices, devices)
      |> push_event("init_map", %{markers: markers})
    }
  end

  @impl true
  def handle_info(%{event: "presence_diff"}, socket = %{assigns: %{map: map}}) do
    {:noreply, assign(socket, devices: Presence.list_presence("map:#{map.id}"))}
  end

  @impl true
  def handle_info({:created_point, point}, socket) do
    create_or_update_marker(point)

    {
      :noreply,
      socket
      |> push_event(
        "created_point",
        %{lat: point.lat, lng: point.lng, device_id: point.device_id}
      )
    }
  end

  defp create_or_update_marker(point) do
    topic = "map:#{point.map_id}"

    if Presence.list(topic) |> Map.has_key?(point.device_id) do
      Presence.update_presence(
        self(),
        topic,
        point.device_id,
        %{current_location: point}
      )
    else
      track(point, topic)
    end
  end

  defp page_title(:show), do: "Show Map"
  defp page_title(:edit), do: "Edit Map"

  defp setup_presence_data(id) do
    if map_size(Presence.list("map:#{id}")) == 0 do
      Loggers.list_points(id)
      |> Enum.group_by(fn p -> p.device_id end)
      |> Enum.map(fn {_device_id, points} -> List.last(points) end)
      |> Enum.each(fn point -> track(point, "map:#{id}") end)
    end
  end

  defp track(point, topic) do
    Presence.track(
      self(),
      topic,
      point.device_id,
      %{id: point.device_id, current_location: point}
    )
  end
end

lib/live_map_view_web/live/modal_component.ex
defmodule LiveMapViewWeb.ModalComponent do
  use LiveMapViewWeb, :live_component

  @impl true
  def render(assigns) do
    ~H"""
    <div
      id={@id}
      class="phx-modal"
      phx-capture-click="close"
      phx-window-keydown="close"
      phx-key="escape"
      phx-target={@myself}
      phx-page-loading>

      <div class="phx-modal-content">
        <%= live_patch raw("&times;"), to: @return_to, class: "phx-modal-close" %>
        <%= live_component @component, @opts %>
      </div>
    </div>
    """
  end

  @impl true
  def handle_event("close", _, socket) do
    {:noreply, push_patch(socket, to: socket.assigns.return_to)}
  end
end

lib/live_map_view_web/live/map_live/form_component.html.heex
<div>
  <h2><%= @title %></h2>

  <.form
    let={f}
    for={@changeset}
    id="map-form"
    phx-target={@myself}
    phx-change="validate"
    phx-submit="save">
  
    <%= label f, :name %>
    <%= text_input f, :name %>
    <%= error_tag f, :name %>
  
    <%= label f, :description %>
    <%= text_input f, :description %>
    <%= error_tag f, :description %>
  
    <div>
      <%= submit "Save", phx_disable_with: "Saving..." %>
    </div>
  </.form>
</div>

lib/live_map_view_web/live/map_live/index.html.heex
<h1>Listing Maps</h1>

<%= if @live_action in [:new, :edit] do %>
  <%= live_modal LiveMapViewWeb.MapLive.FormComponent,
    id: @map.id || :new,
    title: @page_title,
    action: @live_action,
    map: @map,
    return_to: Routes.map_index_path(@socket, :index) %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody id="maps">
    <%= for map <- @maps do %>
      <tr id={"map-#{map.id}"}>
        <td><%= map.name %></td>
        <td><%= map.description %></td>

        <td>
          <span><%= live_redirect "Show", to: Routes.map_show_path(@socket, :show, map) %></span>
          <span><%= live_patch "Edit", to: Routes.map_index_path(@socket, :edit, map) %></span>
          <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: map.id, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%= live_patch "New Map", to: Routes.map_index_path(@socket, :new) %></span>

lib/live_map_view_web/live/map_live/show.html.heex
<%= if @live_action in [:edit] do %>
  <%= live_modal LiveMapViewWeb.MapLive.FormComponent,
    id: @map.id,
    title: @page_title,
    action: @live_action,
    map: @map,
    return_to: Routes.map_show_path(@socket, :show, @map) %>
<% end %>

<div class="row">
  <div class="column column-20">
    <h1>Show Map</h1>
    <ul>
      <li>
        <strong>Name:</strong>
        <%= @map.name %>
      </li>

      <li>
        <strong>Description:</strong>
        <%= @map.description %>
      </li>
    </ul>
    <%= for device <- @devices do %>
      <dl>
        <dt><strong>id: <%= device.id |> String.split("-") |> List.first %></strong></dt>
        <dt>lat: <%= device.current_location.lat %></dt>
        <dt>lng: <%= device.current_location.lng %></dt>
        <dt>at: <%= device.current_location.inserted_at %></dt>
      </dl>
    <% end %>
    <span><%= live_patch "Edit", to: Routes.map_show_path(@socket, :edit, @map), class: "button" %></span>
    <span><%= live_redirect "Back", to: Routes.map_index_path(@socket, :index) %></span>
  </div>
  <div class="column column-80">
    <div id="googleMap" phx-update="ignore" phx-hook="Map">
      <div id="map"></div>
    </div>
  </div>
</div>